// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mon.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// reconnectFlag 连接标识取值
type RECONNECT_FLAG int32

const (
	RECONNECT_FLAG_FIRST    RECONNECT_FLAG = 0
	RECONNECT_FLAG_UNINITED RECONNECT_FLAG = 1
	RECONNECT_FLAG_INITED   RECONNECT_FLAG = 2
)

var RECONNECT_FLAG_name = map[int32]string{
	0: "FIRST",
	1: "UNINITED",
	2: "INITED",
}
var RECONNECT_FLAG_value = map[string]int32{
	"FIRST":    0,
	"UNINITED": 1,
	"INITED":   2,
}

func (x RECONNECT_FLAG) String() string {
	return proto.EnumName(RECONNECT_FLAG_name, int32(x))
}
func (RECONNECT_FLAG) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{0}
}

// 因为socket url直接附带上了基础参数,因此不需要客户端主动的login
type S2CLogin struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{0}
}
func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (dst *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(dst, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func (m *S2CLogin) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *S2CLogin) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// 两个玩家都连上后,广播playerInfo
type S2CPlayerInfo struct {
	Players              []*PlayerInfo `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2CPlayerInfo) Reset()         { *m = S2CPlayerInfo{} }
func (m *S2CPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*S2CPlayerInfo) ProtoMessage()    {}
func (*S2CPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{1}
}
func (m *S2CPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CPlayerInfo.Unmarshal(m, b)
}
func (m *S2CPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CPlayerInfo.Marshal(b, m, deterministic)
}
func (dst *S2CPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CPlayerInfo.Merge(dst, src)
}
func (m *S2CPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_S2CPlayerInfo.Size(m)
}
func (m *S2CPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_S2CPlayerInfo proto.InternalMessageInfo

func (m *S2CPlayerInfo) GetPlayers() []*PlayerInfo {
	if m != nil {
		return m.Players
	}
	return nil
}

type PlayerInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatarurl            string   `protobuf:"bytes,3,opt,name=avatarurl,proto3" json:"avatarurl,omitempty"`
	Teamid               string   `protobuf:"bytes,4,opt,name=teamid,proto3" json:"teamid,omitempty"`
	Opt                  string   `protobuf:"bytes,5,opt,name=opt,proto3" json:"opt,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Ai                   bool     `protobuf:"varint,7,opt,name=ai,proto3" json:"ai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{2}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlayerInfo) GetAvatarurl() string {
	if m != nil {
		return m.Avatarurl
	}
	return ""
}

func (m *PlayerInfo) GetTeamid() string {
	if m != nil {
		return m.Teamid
	}
	return ""
}

func (m *PlayerInfo) GetOpt() string {
	if m != nil {
		return m.Opt
	}
	return ""
}

func (m *PlayerInfo) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *PlayerInfo) GetAi() bool {
	if m != nil {
		return m.Ai
	}
	return false
}

// 客户端准备好后,往服务器发送loading 100,双方都100%后,即开始推送下面的初始化消息
type C2SLoading struct {
	Progress             int32    `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLoading) Reset()         { *m = C2SLoading{} }
func (m *C2SLoading) String() string { return proto.CompactTextString(m) }
func (*C2SLoading) ProtoMessage()    {}
func (*C2SLoading) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{3}
}
func (m *C2SLoading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLoading.Unmarshal(m, b)
}
func (m *C2SLoading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLoading.Marshal(b, m, deterministic)
}
func (dst *C2SLoading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLoading.Merge(dst, src)
}
func (m *C2SLoading) XXX_Size() int {
	return xxx_messageInfo_C2SLoading.Size(m)
}
func (m *C2SLoading) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLoading.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLoading proto.InternalMessageInfo

func (m *C2SLoading) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

// 转发对方的加载进度
type S2COpponentLoading struct {
	Progress             int32    `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2COpponentLoading) Reset()         { *m = S2COpponentLoading{} }
func (m *S2COpponentLoading) String() string { return proto.CompactTextString(m) }
func (*S2COpponentLoading) ProtoMessage()    {}
func (*S2COpponentLoading) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{4}
}
func (m *S2COpponentLoading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COpponentLoading.Unmarshal(m, b)
}
func (m *S2COpponentLoading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COpponentLoading.Marshal(b, m, deterministic)
}
func (dst *S2COpponentLoading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COpponentLoading.Merge(dst, src)
}
func (m *S2COpponentLoading) XXX_Size() int {
	return xxx_messageInfo_S2COpponentLoading.Size(m)
}
func (m *S2COpponentLoading) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COpponentLoading.DiscardUnknown(m)
}

var xxx_messageInfo_S2COpponentLoading proto.InternalMessageInfo

func (m *S2COpponentLoading) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

// 心跳,客户端无其他业务请求时，每2秒发送
type C2SHeart struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeart) Reset()         { *m = C2SHeart{} }
func (m *C2SHeart) String() string { return proto.CompactTextString(m) }
func (*C2SHeart) ProtoMessage()    {}
func (*C2SHeart) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{5}
}
func (m *C2SHeart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeart.Unmarshal(m, b)
}
func (m *C2SHeart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeart.Marshal(b, m, deterministic)
}
func (dst *C2SHeart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeart.Merge(dst, src)
}
func (m *C2SHeart) XXX_Size() int {
	return xxx_messageInfo_C2SHeart.Size(m)
}
func (m *C2SHeart) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeart.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeart proto.InternalMessageInfo

func (m *C2SHeart) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type S2CHeart struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CHeart) Reset()         { *m = S2CHeart{} }
func (m *S2CHeart) String() string { return proto.CompactTextString(m) }
func (*S2CHeart) ProtoMessage()    {}
func (*S2CHeart) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{6}
}
func (m *S2CHeart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeart.Unmarshal(m, b)
}
func (m *S2CHeart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeart.Marshal(b, m, deterministic)
}
func (dst *S2CHeart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeart.Merge(dst, src)
}
func (m *S2CHeart) XXX_Size() int {
	return xxx_messageInfo_S2CHeart.Size(m)
}
func (m *S2CHeart) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeart.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeart proto.InternalMessageInfo

func (m *S2CHeart) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type NoData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{7}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoData.Unmarshal(m, b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
}
func (dst *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(dst, src)
}
func (m *NoData) XXX_Size() int {
	return xxx_messageInfo_NoData.Size(m)
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// 下发配置信息
type S2CParams struct {
	MaxGameTimeSecs      int32    `protobuf:"varint,1,opt,name=maxGameTimeSecs,proto3" json:"maxGameTimeSecs,omitempty"`
	MaxStrikeTimeSecs    int32    `protobuf:"varint,2,opt,name=maxStrikeTimeSecs,proto3" json:"maxStrikeTimeSecs,omitempty"`
	MinWinPoints         int32    `protobuf:"varint,3,opt,name=minWinPoints,proto3" json:"minWinPoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CParams) Reset()         { *m = S2CParams{} }
func (m *S2CParams) String() string { return proto.CompactTextString(m) }
func (*S2CParams) ProtoMessage()    {}
func (*S2CParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{8}
}
func (m *S2CParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CParams.Unmarshal(m, b)
}
func (m *S2CParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CParams.Marshal(b, m, deterministic)
}
func (dst *S2CParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CParams.Merge(dst, src)
}
func (m *S2CParams) XXX_Size() int {
	return xxx_messageInfo_S2CParams.Size(m)
}
func (m *S2CParams) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CParams.DiscardUnknown(m)
}

var xxx_messageInfo_S2CParams proto.InternalMessageInfo

func (m *S2CParams) GetMaxGameTimeSecs() int32 {
	if m != nil {
		return m.MaxGameTimeSecs
	}
	return 0
}

func (m *S2CParams) GetMaxStrikeTimeSecs() int32 {
	if m != nil {
		return m.MaxStrikeTimeSecs
	}
	return 0
}

func (m *S2CParams) GetMinWinPoints() int32 {
	if m != nil {
		return m.MinWinPoints
	}
	return 0
}

// 游戏结束
type S2CGameEnd struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Users                []string `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Winner               string   `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Scores               []string `protobuf:"bytes,4,rep,name=scores,proto3" json:"scores,omitempty"`
	Msg                  string   `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGameEnd) Reset()         { *m = S2CGameEnd{} }
func (m *S2CGameEnd) String() string { return proto.CompactTextString(m) }
func (*S2CGameEnd) ProtoMessage()    {}
func (*S2CGameEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{9}
}
func (m *S2CGameEnd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGameEnd.Unmarshal(m, b)
}
func (m *S2CGameEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGameEnd.Marshal(b, m, deterministic)
}
func (dst *S2CGameEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGameEnd.Merge(dst, src)
}
func (m *S2CGameEnd) XXX_Size() int {
	return xxx_messageInfo_S2CGameEnd.Size(m)
}
func (m *S2CGameEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGameEnd.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGameEnd proto.InternalMessageInfo

func (m *S2CGameEnd) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *S2CGameEnd) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *S2CGameEnd) GetWinner() string {
	if m != nil {
		return m.Winner
	}
	return ""
}

func (m *S2CGameEnd) GetScores() []string {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *S2CGameEnd) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 通知玩家, 其他人断线
type S2CDisconnect struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CDisconnect) Reset()         { *m = S2CDisconnect{} }
func (m *S2CDisconnect) String() string { return proto.CompactTextString(m) }
func (*S2CDisconnect) ProtoMessage()    {}
func (*S2CDisconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{10}
}
func (m *S2CDisconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CDisconnect.Unmarshal(m, b)
}
func (m *S2CDisconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CDisconnect.Marshal(b, m, deterministic)
}
func (dst *S2CDisconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CDisconnect.Merge(dst, src)
}
func (m *S2CDisconnect) XXX_Size() int {
	return xxx_messageInfo_S2CDisconnect.Size(m)
}
func (m *S2CDisconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CDisconnect.DiscardUnknown(m)
}

var xxx_messageInfo_S2CDisconnect proto.InternalMessageInfo

// 通知玩家(其他人)上线消息
type OnlineInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Online               bool     `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineInfo) Reset()         { *m = OnlineInfo{} }
func (m *OnlineInfo) String() string { return proto.CompactTextString(m) }
func (*OnlineInfo) ProtoMessage()    {}
func (*OnlineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{11}
}
func (m *OnlineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineInfo.Unmarshal(m, b)
}
func (m *OnlineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineInfo.Marshal(b, m, deterministic)
}
func (dst *OnlineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineInfo.Merge(dst, src)
}
func (m *OnlineInfo) XXX_Size() int {
	return xxx_messageInfo_OnlineInfo.Size(m)
}
func (m *OnlineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineInfo proto.InternalMessageInfo

func (m *OnlineInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *OnlineInfo) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

type S2COnline struct {
	Uids                 []*OnlineInfo `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2COnline) Reset()         { *m = S2COnline{} }
func (m *S2COnline) String() string { return proto.CompactTextString(m) }
func (*S2COnline) ProtoMessage()    {}
func (*S2COnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{12}
}
func (m *S2COnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COnline.Unmarshal(m, b)
}
func (m *S2COnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COnline.Marshal(b, m, deterministic)
}
func (dst *S2COnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COnline.Merge(dst, src)
}
func (m *S2COnline) XXX_Size() int {
	return xxx_messageInfo_S2COnline.Size(m)
}
func (m *S2COnline) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COnline.DiscardUnknown(m)
}

var xxx_messageInfo_S2COnline proto.InternalMessageInfo

func (m *S2COnline) GetUids() []*OnlineInfo {
	if m != nil {
		return m.Uids
	}
	return nil
}

// 踢下线通知.其他终端上线我的账号，我被踢下线
type S2CKickOffline struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CKickOffline) Reset()         { *m = S2CKickOffline{} }
func (m *S2CKickOffline) String() string { return proto.CompactTextString(m) }
func (*S2CKickOffline) ProtoMessage()    {}
func (*S2CKickOffline) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{13}
}
func (m *S2CKickOffline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CKickOffline.Unmarshal(m, b)
}
func (m *S2CKickOffline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CKickOffline.Marshal(b, m, deterministic)
}
func (dst *S2CKickOffline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CKickOffline.Merge(dst, src)
}
func (m *S2CKickOffline) XXX_Size() int {
	return xxx_messageInfo_S2CKickOffline.Size(m)
}
func (m *S2CKickOffline) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CKickOffline.DiscardUnknown(m)
}

var xxx_messageInfo_S2CKickOffline proto.InternalMessageInfo

// 表情
type C2CEmoji struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CEmoji) Reset()         { *m = C2CEmoji{} }
func (m *C2CEmoji) String() string { return proto.CompactTextString(m) }
func (*C2CEmoji) ProtoMessage()    {}
func (*C2CEmoji) Descriptor() ([]byte, []int) {
	return fileDescriptor_mon_e246305d329d0aea, []int{14}
}
func (m *C2CEmoji) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CEmoji.Unmarshal(m, b)
}
func (m *C2CEmoji) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CEmoji.Marshal(b, m, deterministic)
}
func (dst *C2CEmoji) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CEmoji.Merge(dst, src)
}
func (m *C2CEmoji) XXX_Size() int {
	return xxx_messageInfo_C2CEmoji.Size(m)
}
func (m *C2CEmoji) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CEmoji.DiscardUnknown(m)
}

var xxx_messageInfo_C2CEmoji proto.InternalMessageInfo

func (m *C2CEmoji) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*S2CLogin)(nil), "pb.s2cLogin")
	proto.RegisterType((*S2CPlayerInfo)(nil), "pb.s2cPlayerInfo")
	proto.RegisterType((*PlayerInfo)(nil), "pb.PlayerInfo")
	proto.RegisterType((*C2SLoading)(nil), "pb.c2sLoading")
	proto.RegisterType((*S2COpponentLoading)(nil), "pb.s2cOpponentLoading")
	proto.RegisterType((*C2SHeart)(nil), "pb.c2sHeart")
	proto.RegisterType((*S2CHeart)(nil), "pb.s2cHeart")
	proto.RegisterType((*NoData)(nil), "pb.NoData")
	proto.RegisterType((*S2CParams)(nil), "pb.s2cParams")
	proto.RegisterType((*S2CGameEnd)(nil), "pb.s2cGameEnd")
	proto.RegisterType((*S2CDisconnect)(nil), "pb.s2cDisconnect")
	proto.RegisterType((*OnlineInfo)(nil), "pb.OnlineInfo")
	proto.RegisterType((*S2COnline)(nil), "pb.s2cOnline")
	proto.RegisterType((*S2CKickOffline)(nil), "pb.s2cKickOffline")
	proto.RegisterType((*C2CEmoji)(nil), "pb.c2cEmoji")
	proto.RegisterEnum("pb.RECONNECT_FLAG", RECONNECT_FLAG_name, RECONNECT_FLAG_value)
}

func init() { proto.RegisterFile("mon.proto", fileDescriptor_mon_e246305d329d0aea) }

var fileDescriptor_mon_e246305d329d0aea = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0x25, 0x6d, 0xba, 0xe6, 0xfe, 0x46, 0x57, 0x2c, 0x34, 0x45, 0x88, 0x87, 0xc8, 0x4f,
	0x11, 0x42, 0x03, 0x85, 0x3f, 0x12, 0x8f, 0x68, 0xeb, 0x46, 0xc5, 0xd4, 0x4e, 0x5e, 0x11, 0x8f,
	0xc8, 0x73, 0xdc, 0xca, 0xac, 0xb6, 0x23, 0xdb, 0x81, 0x22, 0xf1, 0xce, 0x97, 0xe0, 0xc3, 0x22,
	0x3b, 0xe9, 0xba, 0x81, 0x90, 0xf6, 0x76, 0xcf, 0x3d, 0xc7, 0xd7, 0xbe, 0x39, 0x27, 0x90, 0x4a,
	0xad, 0x8e, 0x6a, 0xa3, 0x9d, 0x46, 0x71, 0x7d, 0x85, 0x5f, 0xc1, 0xd0, 0x96, 0xec, 0x5c, 0xaf,
	0x84, 0x42, 0x63, 0xe8, 0x49, 0xbb, 0xca, 0xa2, 0x3c, 0x2a, 0x52, 0xe2, 0x4b, 0x74, 0x08, 0x03,
	0xc3, 0x6d, 0xb3, 0x76, 0x59, 0x9c, 0x47, 0xc5, 0x90, 0x74, 0x08, 0xbf, 0x85, 0x07, 0xb6, 0x64,
	0x17, 0x6b, 0xfa, 0x9d, 0x9b, 0xa9, 0x5a, 0x6a, 0x54, 0xc0, 0x5e, 0x1d, 0x90, 0xcd, 0xa2, 0xbc,
	0x57, 0xfc, 0x5f, 0x8e, 0x8e, 0xea, 0xab, 0xa3, 0x9d, 0x80, 0x6c, 0x69, 0xfc, 0x2b, 0x02, 0xb8,
	0x75, 0x70, 0x0c, 0xbd, 0x46, 0x54, 0xdb, 0x3b, 0x1b, 0x51, 0x21, 0x04, 0x7d, 0x45, 0x25, 0x0f,
	0x37, 0xa6, 0x24, 0xd4, 0xe8, 0x09, 0xa4, 0xf4, 0x2b, 0x75, 0xd4, 0x34, 0x66, 0x9d, 0xf5, 0x02,
	0xb1, 0x6b, 0xf8, 0x57, 0x3a, 0x4e, 0xa5, 0xa8, 0xb2, 0x7e, 0xa0, 0x3a, 0xe4, 0x67, 0xeb, 0xda,
	0x65, 0x49, 0x3b, 0x5b, 0xd7, 0xce, 0x77, 0x2c, 0xdf, 0x64, 0x83, 0x3c, 0x2a, 0x12, 0xe2, 0x4b,
	0x34, 0x82, 0x98, 0x8a, 0x6c, 0x2f, 0x6c, 0x17, 0x53, 0x81, 0x0b, 0x00, 0x56, 0xda, 0x73, 0x4d,
	0x2b, 0xa1, 0x56, 0xe8, 0x31, 0x0c, 0x6b, 0xa3, 0x57, 0x86, 0x5b, 0x1b, 0x9e, 0x98, 0x90, 0x1b,
	0x8c, 0x5f, 0x00, 0xb2, 0x25, 0x9b, 0xd7, 0xb5, 0x56, 0x5c, 0xb9, 0xfb, 0x9c, 0x28, 0x60, 0xc8,
	0x4a, 0xfb, 0x9e, 0x53, 0xe3, 0xfc, 0x46, 0x4e, 0x48, 0x6e, 0x1d, 0x95, 0x75, 0x10, 0xf6, 0xc8,
	0xae, 0xe1, 0x95, 0xb6, 0x64, 0xf7, 0x51, 0x0e, 0x61, 0x30, 0xd3, 0x27, 0xd4, 0x51, 0xfc, 0x33,
	0x82, 0xd4, 0x9b, 0x42, 0x0d, 0x95, 0x16, 0x15, 0x70, 0x20, 0xe9, 0xe6, 0x8c, 0x4a, 0xbe, 0x10,
	0x92, 0x5f, 0x72, 0xb6, 0x7d, 0xce, 0x9f, 0x6d, 0xf4, 0x0c, 0x1e, 0x4a, 0xba, 0xb9, 0x74, 0x46,
	0x5c, 0xef, 0xb4, 0x71, 0xd0, 0xfe, 0x4d, 0x20, 0x0c, 0xfb, 0x52, 0xa8, 0x4f, 0x42, 0x5d, 0x68,
	0xa1, 0x9c, 0x0d, 0x66, 0x24, 0xe4, 0x4e, 0x0f, 0xff, 0x00, 0xb0, 0x25, 0xf3, 0x97, 0x4c, 0x54,
	0x75, 0x2b, 0x43, 0xad, 0xc9, 0x1d, 0x42, 0x8f, 0x20, 0x69, 0xac, 0x0f, 0x4c, 0x9c, 0xf7, 0x8a,
	0x94, 0xb4, 0xc0, 0xab, 0xbf, 0x09, 0xa5, 0xb8, 0xe9, 0x6c, 0xee, 0x90, 0xef, 0x5b, 0xa6, 0x0d,
	0xb7, 0x59, 0x3f, 0xc8, 0x3b, 0xb4, 0xcd, 0x6c, 0x72, 0x93, 0x59, 0x7c, 0x10, 0xb2, 0x79, 0x22,
	0x2c, 0xd3, 0x4a, 0x71, 0xe6, 0xf0, 0x1b, 0x80, 0xb9, 0x5a, 0x0b, 0xc5, 0xff, 0x11, 0xb8, 0x43,
	0x18, 0xe8, 0xc0, 0x6f, 0x43, 0xde, 0x22, 0xfc, 0x3c, 0x7c, 0xcf, 0xf6, 0x28, 0xc2, 0xd0, 0x6f,
	0x44, 0x75, 0x27, 0xdd, 0xbb, 0xa1, 0x24, 0x70, 0x78, 0x0c, 0x23, 0x5b, 0xb2, 0x0f, 0x82, 0x5d,
	0xcf, 0x97, 0xcb, 0x30, 0x22, 0xf7, 0x8e, 0xb3, 0x89, 0xd4, 0x5f, 0x84, 0xdf, 0x57, 0xa8, 0x8a,
	0x6f, 0x3a, 0x1f, 0x5a, 0xf0, 0xf4, 0x35, 0x8c, 0xc8, 0xe4, 0x78, 0x3e, 0x9b, 0x4d, 0x8e, 0x17,
	0x9f, 0x4f, 0xcf, 0xdf, 0x9d, 0xa1, 0x14, 0x92, 0xd3, 0x29, 0xb9, 0x5c, 0x8c, 0xff, 0x43, 0xfb,
	0x30, 0xfc, 0x38, 0x9b, 0xce, 0xa6, 0x8b, 0xc9, 0xc9, 0x38, 0x42, 0x00, 0x83, 0xae, 0x8e, 0xaf,
	0x06, 0xe1, 0x0f, 0x7e, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x10, 0xfa, 0x34, 0x6c, 0xce, 0x03,
	0x00, 0x00,
}
